CREATE DATABASE test;
\c test;
CREATE TABLE IF NOT EXISTS test(id SERIAL PRIMARY KEY, name TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());

CREATE USER pgtap WITH REPLICATION PASSWORD '123';
GRANT SELECT ON test TO pgtap;
GRANT postgres TO pgtap;
